export const galleryIntro = {
  backLabel: "Regresar al inicio",
  backHref: "/",
  tagline:
    "Es un estudio donde vive solo la creatividad, la disciplina y el buen criterio.",
} as const;

export const galleryItems = [
  {
    id: "health-deal",
    src: "/images/gallery/health-deal.png",
    alt: "Health.deal — sitio web de derivaciones médicas",
    title: "Health.deal",
    tags: "Diseño web",
    width: 706,
    height: 439,
    span: "lg:col-span-6",
  },
  {
    id: "zara-app",
    src: "/images/gallery/zara-app.png",
    alt: "Zara AI English Coach — app en iPhone",
    title: "Zara AI English Coach",
    tags: "Diseño de App, branding",
    width: 340,
    height: 439,
    span: "lg:col-span-3",
  },
  {
    id: "zara-hand",
    src: "/images/gallery/zara-hand.png",
    alt: "Zara AI English Coach — mano sosteniendo el teléfono",
    title: "Zara AI English Coach",
    tags: "Diseño de App, branding",
    width: 339,
    height: 439,
    span: "lg:col-span-3",
  },
  {
    id: "frust-statement",
    src: "/images/gallery/frust-statement.png",
    alt: "Frust — estado de cuenta y ahorros",
    title: "Frust",
    tags: "Diseño web, branding, Design System, Cursor",
    width: 347,
    height: 439,
    span: "lg:col-span-3",
  },
  {
    id: "frust-aws",
    src: "/images/gallery/frust-aws.png",
    alt: "Frust — landing de ahorro en AWS",
    title: "Frust",
    tags: "Diseño web, branding, Design System, Cursor",
    width: 698,
    height: 439,
    span: "lg:col-span-6",
  },
  {
    id: "lapzo-desktop",
    src: "/images/gallery/lapzo-desktop.png",
    alt: "Lapzo — dashboard de desarrollo de equipos",
    title: "Lapzo",
    tags: "Diseño web, branding, Design System, Webflow",
    width: 698,
    height: 439,
    span: "lg:col-span-6",
  },
  {
    id: "lapzo-hand",
    src: "/images/gallery/lapzo-hand.png",
    alt: "Lapzo — app en iPhone",
    title: "Lapzo",
    tags: "Diseño web, branding, Design System, Webflow",
    width: 339,
    height: 439,
    span: "lg:col-span-3",
  },
  {
    id: "enjoy-cap",
    src: "/images/gallery/enjoy-cap.png",
    alt: "Enjoy the Club — gorra de merchandising",
    title: "Enjoy the Club",
    tags: "Branding, diseño web, merchandising",
    width: 347,
    height: 439,
    span: "lg:col-span-3",
  },
  {
    id: "enjoy-ig-1",
    src: "/images/gallery/enjoy-ig-1.png",
    alt: "Enjoy the Club — pieza de Instagram",
    title: "Enjoy the Club",
    tags: "Branding, diseño web, merchandising",
    width: 339,
    height: 439,
    span: "lg:col-span-3",
  },
  {
    id: "enjoy-ig-2",
    src: "/images/gallery/enjoy-ig-2.png",
    alt: "Enjoy the Club — pieza de Instagram con lentes",
    title: "Enjoy the Club",
    tags: "Branding, diseño web, merchandising",
    width: 347,
    height: 439,
    span: "lg:col-span-3",
  },
  {
    id: "enjoy-billboard",
    src: "/images/gallery/enjoy-billboard.png",
    alt: "Enjoy the Club — valla publicitaria",
    title: "Enjoy the Club",
    tags: "Branding, diseño web, merchandising",
    width: 698,
    height: 439,
    span: "lg:col-span-6",
  },
  {
    id: "frust-hoodie",
    src: "/images/gallery/frust-hoodie.png",
    alt: "Frust — hoodie de merchandising",
    title: "Frust",
    tags: "Branding, diseño web, merchandising",
    width: 339,
    height: 439,
    span: "lg:col-span-3",
  },
  {
    id: "frust-caps",
    src: "/images/gallery/frust-caps.png",
    alt: "Frust — gorras de merchandising",
    title: "Frust",
    tags: "Branding, diseño web, merchandising",
    width: 589,
    height: 439,
    span: "lg:col-span-5",
  },
  {
    id: "frust-hoodie-crop",
    src: "/images/gallery/frust-hoodie-crop.png",
    alt: "Frust — detalle del hoodie",
    title: "Frust",
    tags: "Branding, diseño web, merchandising",
    width: 457,
    height: 439,
    span: "lg:col-span-4",
  },
] as const;

export type GalleryItem = (typeof galleryItems)[number];
